import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGitlab,
  AiFillInstagram,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import React, { useState } from "react";
import Image from "next/image";
import web1 from "../public/web1.png";
import me from "../public/me.png";
import backend from "../public/backend.png";
import creator from "../public/creator.png";
import mobile from "../public/mobile.png";
import web from "../public/web.png";
import css from "../public/css.png";
import docker from "../public/docker.png";
import html from "../public/html.png";
import javascript from "../public/javascript.png";
import nodejs from "../public/nodejs.png";
import reactjs from "../public/reactjs.png";
import tailwind from "../public/tailwind.png";
import django from "../public/django-icon.svg";
import git_logo from "../public/git.png";
import fastapi from "../public/fastapi.png"
import postgres from "../public/postgres.svg"
import python from "../public/python.png"
import car from "../public/car2.png"


export default function Home() {
  const [darkMode, setDarkMode] = useState(null);


  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jaspreet Sangha Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">

        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons">DEVJAS</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" /></li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="https://docs.google.com/document/d/1Ap9-z73_ofMyv9GGq2Ki51y3kOY-9iy3sbxBuYhTj0A/edit">Resume</a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Jaspreet Sangha</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Full-Stack Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">I'm based in Sacramento, CA who prides himself in constructing both the back-end and front-end of an appliation to generate amazing user experiences.</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <a href="https://www.linkedin.com/in/jaspreet-sanghaswe/"><AiFillLinkedin /></a>
            <a href="https://gitlab.com/IamYorye"><AiFillGitlab /></a>
            <a href="https://www.instagram.com/jaspree.t.sangha/"><AiFillInstagram /></a>
          </div>
          <div className="relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            < Image alt="" src={me} objectFit="cover" layout="fill" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-l py-1 font-medium  text-teal-600">INTRODUCTION</h3>
            <h4 className="text-4xl py-1 font-medium  text-teal-600">Overview</h4>
            <p className="text-sm py-2 leading-8 text-gray-800 dark:text-white">
              I'm a skilled <span className="text-teal-500">software engineer</span> with experience in <span className="text-teal-500">Python</span> and <span className="text-teal-500">Javascript</span>, and plenty of experience in utilizing frameworks like <span className="text-teal-500">React</span>, <span className="text-teal-500">Django</span> and <span className="text-teal-500">Node.js</span>. I'm a <span className="text-teal-500">quick learner</span> and a very <span className="text-teal-500">collaborative</span> individual who works closely with both my team and clients to create efficient, highly scalable, and user-friendly applications to make the world a better place. Let's start working together to change the world!
            </p>
          </div>
          <div className="lg:flex gap-20 justify-center">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={web} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Front-End Developer</h3>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={mobile} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">React.js Developer</h3>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={backend} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Back-End Developer</h3>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={creator} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Full-Stack Developer</h3>
            </div>
          </div>
        </section>

        <section>
          <div className="lg:flex gap-3">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={html} width={100} height={100} className="mx-auto" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={css} width={100} height={100} className="mx-auto" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={javascript} width={100} height={100} className="mx-auto" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={python} width={100} height={100} className="mx-auto" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={reactjs} width={100} height={100} className="mx-auto" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={tailwind} width={100} height={100} className="mx-auto" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={nodejs} width={100} height={100} className="mx-auto" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={docker} width={100} height={100} className="mx-auto" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={django} width={100} height={100} className="mx-auto" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={fastapi} width={100} height={100} className="mx-auto" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={git_logo} width={100} height={100} className="mx-auto" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image alt="" src={postgres} width={100} height={100} className="mx-auto" />
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-l py-1 font-medium  text-teal-600">MY WORK</h3>
            <h4 className="text-4xl py-1 font-medium  text-teal-600">Projects</h4>
            <p className="text-sm py-2 leading-8 text-gray-800 dark:text-white">
              The following projects showcase the skills I've required through my journey of becoming a software engineer.  Each project is breifly describled with links to code, repositories and live demos in it.  All these projects demonstrate my ability to solve complex problems, work with technologies I've just been introduced to, and manage both time and teamwork effectively.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-5 lg:flex-row lg:flex-wrap">
            <div className="basis 1/3 flex-5">
              <a href="https://gitlab.com/planiteers/project-plan-it"><Image alt="" src={web1} className="rounded-lg" /></a>
            </div>
            <div className="basis 1/3 flex-5">
              <a href="https://gitlab.com/IamYorye/carppointment"><Image alt="" src={car} className="rounded-lg" /></a>
            </div>
          </div>
        </section>
      </main>

    </div>
  );
}
